-- -- Create the projects table from scratch with no dependencies
-- CREATE TABLE projects (
--   id TEXT PRIMARY KEY,
--   name TEXT,
--   type TEXT,
--   description TEXT,
--   date_modified TIMESTAMP,
--   size TEXT,
--   status TEXT,
--   created_at TIMESTAMP DEFAULT NOW(),
--   updated_at TIMESTAMP DEFAULT NOW()
-- );

-- -- Create the user_projects junction table
-- CREATE TABLE user_projects (
--   id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
--   user_id TEXT NOT NULL,
--   project_id TEXT NOT NULL,
--   role TEXT NOT NULL DEFAULT 'owner',
--   UNIQUE(user_id, project_id)
-- );

-- -- Create indexes for better performance
-- CREATE INDEX idx_user_projects_user_id ON user_projects(user_id);
-- CREATE INDEX idx_user_projects_project_id ON user_projects(project_id);
